#!/bin/bash
# This is a bash script.
# Put your description below this line and code below that.
# 
echo
echo "Installing ble.sh(bash syntax highlighting. . ."
sleep 1

if [[ ! -d $HOME/"Modules&Apps" ]]; then
	mkdir $HOME/"Modules&Apps"
fi
cd $HOME/"Modules&Apps"
git clone https://github.com/akinomyoga/ble.sh.git
cd ble.sh
make
source out/ble.sh
make INSDIR="$HOME/.local/share/blesh" install
sleep 1

echo
echo "If not already done, add the folling lines to your .bashrc file. The first section is to be added after 'export TERM' line in your .bashrc file. The second section is to be added the bottom of your .bashrc file.

# blesh, bash syntax highlighting.
[[ \$- == *i* ]] && source \"\$HOME/.local/share/blesh/ble.sh\" --attach=none


# blesh, bash syntax highlighting.
((_ble_bash)) && ble-attach"

cd
