#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo "Creating directories. . ."
if [[ ! -d /mnt/chroot ]]; then
	echo
	echo "Sudo creating and cleaning dir /mnt/chroot. . ."
	sudo mkdir /mnt/chroot
else
	echo
	echo "Sudo creating and cleaning dir /mnt/chroot. . ."
	sudo rm -rf /mnt/chroot/*
fi
sleep 1

echo
echo "${ILCOLOR3}Mounting a folder for full chroot.${ILRESTORE}"
echo
sleep 1

echo "${ILCOLOR3}Showing drives:${ILRESTORE} "
lsblk
sleep 1

echo
read -p "${ILCOLOR3}Type device in which you would like to mount the main file system(ex. /dev/sdb1):${ILRESTORE} " MNT_DVC
sleep 1

echo
echo "Mounting with: sudo mount $MNT_DVC /mnt/chroot"
sudo mount $MNT_DVC /mnt/chroot
sleep 1

function dev_mnt(){
echo
read -p "${ILCOLOR3}Type any other devices to mount(ex. /dev/sda2. This is for separate home and/or boot partitions)? Leave blank for none:${ILRESTORE} " MNT_DVC2
sleep 1

if [[ ! $MNT_DVC2 = "" ]]; then
	echo
	read -p "${ILCOLOR3}What folder to mount $MNT_DVC2 to(ex. home, boot, etc.)${ILRESTORE} " MNT_DVC2_FLDR
	sleep 1
	echo "Mounting with: sudo mount $MNT_DVC2 \"/mnt/chroot/$MNT_DVC2_FLDR\""
	sudo mount "$MNT_DVC2" "/mnt/chroot/$MNT_DVC2_FLDR"
	sleep 1
	dev_mnt
else
	echo
	echo "${ILCOLOR3}No other device selected.${ILRESTORE}"
	sleep 1
fi
}
dev_mnt

echo
echo "${ILCOLOR3}Mounting other needed drives to /mnt.${ILRESTORE}"
echo "for i in /dev /dev/pts /proc /sys /run; do sudo mount -B $i /mnt/chroot$i; done"
for i in /dev /dev/pts /proc /sys /run; do sudo mount -B $i /mnt/chroot$i; done
sleep 1

echo
echo "Adding resolv.conf for connection with: sudo cp /etc/resolv.conf /mnt/etc/"
sudo cp /etc/resolv.conf /mnt/chroot/etc/
cp
sleep 1

echo
echo "${ILCOLOR3}Chroot'ing now. . .${ILRESTORE}"
echo "sudo chroot /mnt/chroot"
sudo chroot /mnt/chroot /bin/bash -x << 'EOF'
su -
echo
echo "Selecting a user to login too. . ."
sleep 1

echo
echo "Showing users. . ."
sleep 1
for usr in $(ls /home); do
        echo $usr
        sleep .25
done | sed 's:lost+found::g'
sleep 1

echo
read -p "Please select a username from list above: " usr_nme
sleep 1

echo
echo "Running command: exec su - $usr_nme"
sleep 1
echo "After command has run and user is logged in, type: 'bash' to load custom bash profile."
sleep 2
exec su - $usr_nme && /bin/bash
EOF

echo
echo "${ILCOLOR3}Exiting script. . .${ILRESTORE}"
sleep 1 

echo
echo "Unmounting drives. . ."
sudo umount -f /mnt/chroot/dev/pts
sudo umount -f /mnt/chroot/dev
sudo umount -f /mnt/chroot/proc
sudo umount -f /mnt/chroot/sys
sudo umount -f /mnt/chroot/run
sudo umount -f /mnt/chroot/boot
sudo umount -f /mnt/chroot/home
sudo umount -f /mnt/chroot
sleep 1

echo
echo "All done!"
sleep 1
