#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo
echo "${ILCOLOR3}Mounting a folder for full chroot.${ILRESTORE}"
echo
sleep 1

echo "${ILCOLOR3}Showing drives:${ILRESTORE} "
lsblk
sleep 1

echo
read -p "${ILCOLOR3}Type device in which you would like to mount the main file system(ex. /dev/sdb1):${ILRESTORE} " MNT_DVC
sleep 1

echo
echo "Mounting with: sudo mount $MNT_DVC /mnt"
sudo mount $MNT_DVC /mnt
sleep 1

function dev_mnt(){
echo
read -p "${ILCOLOR3}Type any other devices to mount(ex. /dev/sda2. This is for separate home and/or boot partitions)? Leave blank for none:${ILRESTORE} " MNT_DVC2
sleep 1

if [[ ! $MNT_DVC2 = "" ]]; then
	echo
	read -p "${ILCOLOR3}What folder to mount $MNT_DVC2 to(ex. home, boot, etc.)${ILRESTORE} " MNT_DVC2_FLDR
	sleep 1
	echo "Mounting with: sudo mount $MNT_DVC2 \"/mnt/$MNT_DVC2_FLDR\""
	sudo mount "$MNT_DVC2" "/mnt/$MNT_DVC2_FLDR"
	sleep 1
	dev_mnt
else
	echo
	echo "${ILCOLOR3}No other device selected.${ILRESTORE}"
	sleep 1
fi
}
dev_mnt

echo
echo "${ILCOLOR3}Mounting other needed drives to /mnt.${ILRESTORE}"
echo "for i in /dev /dev/pts /proc /sys; do sudo mount -B $i /mnt$i; done"
for i in /dev /dev/pts /proc /sys /run; do sudo mount -B $i /mnt$i; done
sleep 1

echo
echo "Adding resolv.conf for connection with: sudo cp /etc/resolv.conf /mnt/etc/"
sudo cp /etc/resolv.conf /mnt/etc/
sleep 1

echo
echo "${ILCOLOR3}Chroot'ing now. . .${ILRESTORE}"
echo "sudo chroot /mnt"
sudo chroot /mnt

echo
echo "${ILCOLOR3}Exiting script. . .${ILRESTORE}"
sleep 1
