#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo
echo
echo "This will clone one drive to another. If you are cloning to a USB, please make sure you run 'wipe-usb' first."
read -p "Would you like to run 'wipe-usb' now?(y/N) " WPE
if [[ "$WPE" =~ ^([yY][eE][sS]|[yY])$ ]]; then
	$HOME/scripts/wipe-usb
else
	echo "Not wiping. . ."
	echo
	sleep 1

	# Create folers if the don't exist.
	CLONE1="$HOME/tmp/clone"
	MOUNT_CLONE1="$HOME/tmp/mount_clone"
	MOUNT_DEST1="$HOME/tmp/mount_dest"
	if [[ ! -d $CLONE1 ]]; then
		mkdir $CLONE1
	fi
	if [[ ! -d $MOUNT_CLONE1 ]]; then
		mkdir $MOUNT_CLONE1
	fi
	if [[ ! -d $MOUNT_DEST1 ]]; then
		mkdir $MOUNT_DEST1
	fi

	# List drives if coping USB.
	echo "Listing drives. . ."
	sleep 1
	lsblk

	# Ask what drive to clone.
	echo
	read -p 'Which drive would you like to clone(ex. /dev/sdb, home/msifland/scripts, etc.)? ' DRIVE1
	echo
	# Check if USB, if so then mount to above folders.
	echo "You selected $DRIVE1 as your drive to clone."
	DRVMNT1=$DRIVE1/*
	if [[ -b $DRIVE1 ]]; then
		echo
		echo "$DRIVE1 is a USB drive or full disk partition, must mount first. Mounting now. . ."
		sleep 1
		sudo mount $DRIVE1 $HOME/tmp/mount_clone
		DRVMNT1=$HOME/tmp/mount_clone/*
		# This checks exit status for error from output.
		if [ $? -eq 0 ]; then
			echo
			echo "${ILCOLOR3}Mount is good.${ILRESTORE}"
			sleep 1
		else
			echo
			echo "${ILCOLOR3}Something went wrong!!!${ILRESTORE}"
			sleep 1
		fi
	fi
	echo
	sleep 1

	# Ask what destination drive to use.
	echo
	read -p 'What is your destination drive(ex. /dev/sdc, $HOME/my-dir, etc.)? If not a USB drive then type "d" for defaut folder $HOME/tmp/clone: ' DRIVE2
	if [[ ! $DRIVE2 =~ ^([dD])$ ]]; then
		echo
		# Check if USB, if so then mount to above folders.
		echo "You selected $DRIVE2 as your destination drive."
		DRVMNT2=$DRIVE2
		sleep 1
		if [[ -b $DRIVE2 ]]; then
			echo
			echo "$DRIVE2 is a USB drive, must mount first."
			sleep 1
			echo "Wiping device. . ."
			sleep 1
			sudo wipefs --all --force $DRIVE2
			echo "Formatting to ext4 for linux drives. . ."
			sleep 1
			sudo mkfs.ext4 -L "Linux" $DRIVE2 | sudo pv -trebI
			echo "Mounting Now"
			sleep 1
			sudo mount $DRIVE2 $HOME/tmp/mount_dest
			DRVMNT2=$HOME/tmp/mount_dest/
		else
			if [[ ! -d $DRIVE2 ]]; then
				mkdir $DRIVE2
			fi
		fi
	else
		DRVMNT2=$HOME/tmp/clone/
		rm -rf $CLONE1/*
	fi
	echo
	sleep 1

	echo
	echo 'Running command: sudo rsync -aurlpEovxHAXW --progress --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"}' $DRVMNT1 $DRVMNT2
	echo
	sleep 1

	# Clone
	#sudo cp -axv $DRVMNT1 $DRVMNT2
	sudo rsync -aurlpEovxHAXW --progress --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} $DRVMNT1 $DRVMNT2

	echo
	echo "Modifying fstab. . ."
	GRB_INST=$(echo $DRVMNT2 | sed 's:[0-9]::g')
	FST_HME=$(blkid | grep -iwq "home" | awk '{print $3}' | sed 's:"::g')
	FST_DRV=$(blkid | grep -iwq "$DRVMNT2" | awk '{print $3}' | sed 's:"::g')
	sudo rm -rf $DRVMNT2/etc/fstab
	touch $HOME/tmp/fstab
	echo "$FST_DRV /               ext4    errors=remount-ro 0       1" > $HOME/tmp/fstab
	echo "" >> $HOME/tmp/fstab
	if blkid | grep -iwq "home"; then
	echo "$FST_HME /home           ext4    defaults        0       2" >> $HOME/tmp/fstab
	echo "" >> $HOME/tmp/fstab
	fi
	echo "/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0" >> $HOME/tmp/fstab
	sudo cp $HOME/tmp/fstab "$DRIVE2/etc/"
	sleep 1

	echo
	echo "Installing grub on $GRB_INST. . ."
	sudo grub-install $GRB_INST
	sudo update-grub $GRB_INST
	sleep 1
	
	# Unmount, if mounted.
	if [[ -b $DRIVE1 ]]; then
		sudo umount $DRIVE1
	fi
	if [[ -b $DRIVE2 ]]; then
		sudo umount $DRIVE2
	fi

	echo
	echo "Done."
	echo
	#rm -rf $CLONE1
	#rm -rf $MOUNT_CLONE1
	#rm -rf $MOUNT_DEST1
	if [ $? -eq 0 ]; then
		echo
		echo "${ILCOLOR3}Mount is good.${ILRESTORE}"
		sleep 1
	else
		echo
		echo "${ILCOLOR3}Something went wrong!!!${ILRESTORE}"
		sleep 1
	fi
fi
exit
