#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
sleep 60
cd
env $(cat ~/scripts/cron_scripts/env-environment) /usr/bin/xterm -e "bash -c \"source ~/.bashrc; clear; $HOME/scripts/conky-check\""
