#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
# Check if script has been run as root.
if [[ ! "$USER" = "root" ]]; then
	echo "This script must be run as root!"
	exit
fi

INST_PTH="/mnt/deb-inst"
echo
echo
echo "This script is set up to install Debian Mate chroot environment. Then create a live-iso file to put on a usb drive."
echo
sleep 1
echo
read -p "Are you ready to continue?[y/N] " YNCON
if [[ $YNCON =~ ^([yY][eE][sS]|[yY])$ ]]; then
	echo
	echo "Ok, moving forward with install..."
	sleep 1
else
	echo
	echo "Ok, exiting script..."
	sleep 1
	exit
fi

# Unmounting all
sudo umount -a
sudo umount $INST_PTH/proc
sudo umount $INST_PTH/sys
sudo umount $INST_PTH/dev/pts
sudo umount $INST_PTH/dev
sudo umount $INST_PTH
sleep 1
# Re-mounting boot for main if it exists.
if blkid | grep -i "boot"; then
	blk_mnt=$(blkid | grep -i "boot" | awk '{ print $1 }')
	sudo mount $blk_mnt /boot
fi

if [[ -d $INST_PTH ]]; then
	echo
	echo "Removing previous install directory $INST_PTH. . ."
	echo
	sleep 1
	sudo rm -rf $INST_PTH
fi

echo
echo "Creating work directories. . ."
echo
sleep 1
cd /
if [[ ! -d /mnt ]]; then
	mkdir /mnt
fi
if [[ ! -d $INST_PTH ]]; then
	mkdir $INST_PTH
fi
if [[ ! -d $INST_PTH/work ]]; then
	mkdir $INST_PTH/work
fi
cd $INST_PTH/work

echo
echo "Downloading debootstrap. . ."
echo
sleep 1
DEBOOT_STRP=$(wget -qO- http://ftp.debian.org/debian/pool/main/d/debootstrap | grep "all.deb" | sort -V | tail -1 | sed -e 's:.*a href="::' -e 's:.>.*::' )
wget http://ftp.debian.org/debian/pool/main/d/debootstrap/"$DEBOOT_STRP"

cd /
dpkg -i $INST_PTH/work/*.deb
sleep 1

#####################################################
echo
echo "Installing to $INST_PTH for .iso build later."
sleep 1

	echo
	echo "Setting up install path as $INST_PTH..."
	part_name=$INST_PTH
	sleep 1
#######################################

debootstrap --arch=amd64 --components=main,non-free,non-free-firmware,contrib testing $INST_PTH http://ftp.us.debian.org/debian/

echo
echo "Mounting system folders and copying /etc files for internet connection. . ."
echo
sleep 1
sudo mount -t proc /proc $INST_PTH/proc
sudo mount -t sysfs /sys $INST_PTH/sys
sudo mount -o bind /dev $INST_PTH/dev
sudo mount -o bind /dev/pts $INST_PTH/dev/pts
sudo cp /etc/network/interfaces $INST_PTH/etc/network/interfaces
sudo cp /etc/resolv.conf $INST_PTH/etc/resolv.conf
sudo cp /etc/hosts $INST_PTH/etc/hosts
sudo cp /etc/hostname $INST_PTH/etc/hostname
if [[ -f $INST_PTH/etc/apt/sources.list ]]; then
	sudo rm -rf $INST_PTH/etc/apt/sources.list
fi
sudo cp /etc/apt/sources.list.d/debian.sources $INST_PTH/etc/apt/sources.list.d/
sudo cp $HOME/MSI_live-build/my_configs/my_preferences.pref $INST_PTH/etc/apt/preferences.d/
sudo nano $INST_PTH/etc/apt/sources.list.d/debian.sources
sudo cp $HOME/scripts/debian-install-continue-iso $INST_PTH/debian-install-continue-iso
sudo cp -arf /usr/share/terminfo/* $INST_PTH/usr/share/terminfo/
sudo cp $HOME/MSI_live-build/my_configs/my_packs.list.chroot $INST_PTH/

echo
echo "Chroot'ing into new install to finish the process. . ."
echo
sleep 1
cat << EOF | part_name="$part_name" sudo chroot $INST_PTH env /bin/bash
source /debian-install-continue-iso
EOF
sudo rm -rf $INST_PTH/debian-install-continue-iso
sudo rm -rf $INST_PTH/my_packs.list.chroot
sudo nano $INST_PTH/etc/apt/sources.list.d/debian.sources


##########################################
if ! dpkg --get-selections | grep -wq "xterm"; then
	apt install xterm
fi
sleep 1

echo
usrnme=$(<$INST_PTH/usrnme.txt)
rm -rf $INST_PTH/{usrnme.txt,usrnme_psswrd.txt,new_psswrd.txt,usrnme_psswrd.txt}
echo "Username is $usrnme"
echo "Creating standard directories. . ."
sleep 1
USR_PTH="$INST_PTH/home/$usrnme"
for dir in \
        $USR_PTH/Downloads \
        $USR_PTH/Documents \
        $USR_PTH/"Modules-Apps" \
        $USR_PTH/pkg_bkups \
        $USR_PTH/Projects \
        $USR_PTH/scripts \
        $USR_PTH/Templates \
        $USR_PTH/Music \
        $USR_PTH/MSI_live-build \
        $USR_PTH/Pictures \
        $USR_PTH/Videos \
        $USR_PTH/tmp \
        $USR_PTH/Wallpapers
do
    if [[ ! -d "$dir" ]]; then
    	echo "Making $dir"
    	mkdir "$dir"
    else
    	echo "$dir exists"
    fi
    sleep .25
done
sleep 1

echo
read -p "Would you like to install your personal files for this installation(scripts, pkg_bkups, Documents, etc.[y/n]? " per_fls
sleep 1
if [[ "$per_fls" =~ ^([yY][eE][sS]|[yY])$ ]]; then
	echo "Copying config files from your personal docs to new system, this will take a while. . ."
	rsync -a --exclude=".git" $HOME/Documents $INST_PTH/home/$usrnme/
	rsync -a --exclude=".git" $HOME/"Modules-Apps" $INST_PTH/home/$usrnme/ 
	rsync -a --exclude=".git"  $HOME/pkg_bkups $INST_PTH/home/$usrnme/
	rsync -a --exclude=".git"  $HOME/Projects $INST_PTH/home/$usrnme/
	rsync -a --exclude=".git"  $HOME/scripts $INST_PTH/home/$usrnme/
	rsync -a --exclude=".git"  $HOME/usb_pkg_bkups $INST_PTH/home/$usrnme/
	rsync -a --exclude=".git"  $HOME/MSI_live-build/my_configs $INST_PTH/home/$usrnme/MSI_live-build/
	echo "Files copied."
	sleep 2
fi

echo 
read -p "Would you like to install your config files for this installation(.config, .local, .cache, etc.[y/n]? " con_fls
sleep 1
if [[ "$con_fls" =~ ^([yY][eE][sS]|[yY])$ ]]; then
	echo "Copying config files from current system to new system, this will take a while. . ."
	rsync -a --exclude="chrome-remote-desktop" --exclude="chromium" --exclude="google-chrome" --exclude="skypeforlinux" --exclude="Code" --exclude="variety" $HOME/.config $INST_PTH/home/$usrnme/
	rsync -a --exclude="share/applications" --exclude="share/baloo" --exclude="share/akonadi" --exclude="share/lutris" --exclude="share/Steam" --exclude="share/Trash" --exclude="share/data" $HOME/.local $INST_PTH/home/$usrnme/
	rsync -a --exclude="chromium" --exclude="chrome-remote-desktop" --exclude="mozilla" --exclude="tracker" --exclude="wine*" --exclude="google-chrome" --exclude="at-spi*" $HOME/.cache $INST_PTH/home/$usrnme/
	rsync -a $HOME/.Xresources $INST_PTH/home/$usrnme/
	rsync -a $HOME/.conkyrc $INST_PTH/home/$usrnme/
    rsync -a $HOME/.conkyrc.bak $INST_PTH/home/$usrnme/
	rsync -a $HOME/.bashrc $INST_PTH/home/$usrnme/
	echo "Files copied. You may want to look at and delete some autostart files from .config/autostart."
	sleep 2
fi

echo
##################################################

echo
echo "Updating permissions to $usrnme"
sleep 1
sudo chown -R $usrnme:$usrnme $INST_PTH/home/$usrnme
echo
read -p "Pausing in case you missed something. You can open a new termianl and chroot back into enviroment(sudo chroot $INST_PTH /bin/sh), or open file explorer to $INST_PTH. Press [ENTER] to finish the process."
sleep 1

echo
echo "Making sure ownership is correct on /home/$usrnme directory. . ."
sudo chown -R $usrnme:$usrnme $INST_PTH/home/$usrnme
sleep 1
sudo cp $HOME/MSI_live-build/my_configs/msifland $INST_PTH/etc/sudoers.d/
$HOME/scripts/debian-install-make-live-iso
echo
echo "Attempting to umount devices and system files. . ."
echo
sleep 1
# Unmounting all
sudo umount -a
sudo umount $INST_PTH/proc
sudo umount $INST_PTH/sys
sudo umount $INST_PTH/dev/pts
sudo umount $INST_PTH/dev
sudo umount $INST_PTH
# Re-mounting boot for main if it exists.
if blkid | grep -i "boot"; then
	blk_mnt=$(blkid | grep -i "boot" | awk '{ print $1 }')
	sudo mount $blk_mnt /boot
fi
echo
echo "All done. Now you can copy to a usb stick. Open file, extract initrd and vmlinuz to same dir as .iso file, and tell /etc/grub.d/40_cusotm to point to it."
echo
sleep 1

exit
