#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.

clear
echo "${ILCOLOR4}              ###########    Updating your system now   ###########${ILRESTORE}"
echo -e ${ILCOLOR2}
echo $(date +%m-%d-%Y) $(date +"%r")
tm_wh_start=$(date +"%s")
echo -e ${ILRESTORE}
sleep 1
echo "${ILCOLOR2}Updating $(uname --all)${ILRESTORE}"
sleep 1

# Password to run as sudo.
PW="spike"
echo
echo "${ILCOLOR1}Updating sources and checking for app updates. . .${ILRESTORE}"

# This sets sudo for the remainder of scripts.
echo $PW | sudo -S echo "${ILCOLOR3}Running as sudo. . .${ILRESTORE}"
sudo apt update -y
sudo apt upgrade -y
sleep 1

echo
echo "${ILCOLOR1}Checking for system upgrade. . .${ILRESTORE}"
sudo apt full-upgrade -y
sudo apt dist-upgrade -y
sleep 1

echo
echo "${ILCOLOR1}Checking for old apps. . .${ILRESTORE}"
sudo apt autoremove -y
sleep 1

echo
echo "${ILCOLOR1}Cleaning up system. . .${ILRESTORE}"
sudo apt clean -y
sudo apt autoclean -y
sudo apt purge -y $(dpkg --list |grep '^rc' |awk '{print $2}')
rm -v -f ~/.cache/thumbnails/*/*.png ~/.thumbnails/*/*.png
rm -v -f ~/.cache/thumbnails/*/*/*.png ~/.thumbnails/*/*/*.png
sleep 1

# Set backups folders and files, and only keep 3 of each.
DEST="$HOME/pkg_bkups"
if [[ ! -d "$DEST" ]]; then
	mkdir $DEST
else
	if ls $DEST/* 1> /dev/null 2>&1; then
		ls $DEST/* -t | sed -e '1,4d' | xargs -d '\n' rm -f > /dev/null 2>&1
	fi
fi
if [[ ! -d "$DEST/apt" ]]; then
	mkdir "$DEST/apt"
fi
if [[ ! -d "$DEST/apt.old" ]]; then
	mkdir "$DEST/apt.old"
fi
if [[ ! -d "$DEST/apt.old-1" ]]; then
	mkdir "$DEST/apt.old-1"
fi

# Rename .old lists to .old-1
if [[ -f $DEST/pkgs.txt.old ]]; then
	mv $DEST/pkgs.txt.old $DEST/pkgs.txt.old-1
fi

# Rename lists to .old
if [[ -f $DEST/pkgs.txt ]]; then
	mv $DEST/pkgs.txt $DEST/pkgs.txt.old
fi
echo
sleep 1

# Creating list for restore purposes.
echo
echo "${ILCOLOR2}Creating list of apps, and copying repos installed on system for restore purposes later. . .${ILRESTORE}"
dpkg --get-selections | awk '{print $1}' > $DEST/pkgs.txt

# This section copies /etc/apt folder and keeps 3 copies.
if ls $DEST/apt.old-1/* > /dev/null 2>&1; then
	rm -rf $DEST/apt.old-1/*
fi
if ls $DEST/apt.old/* > /dev/null 2>&1; then
	cp -rf $DEST/apt.old/* $DEST/apt.old-1/
	rm -rf $DEST/apt.old/*
fi
if ls $DEST/apt/* > /dev/null 2>&1; then
	cp -rf $DEST/apt/* $DEST/apt.old/
	rm -rf $DEST/apt/*
fi
cp -rf /etc/apt/* $DEST/apt/
sleep 1

echo
echo "${ILCOLOR1}Backup up .conkyrc, .bashrc, and .zshrc files. . .${ILRESTORE}"
cp -f /home/msifland/{.bashrc,.conkyrc,.conkyrc.bak,.zshrc} /home/msifland/pkg_bkups/backups/
sleep 1

echo
echo "${ILCOLOR1}Backing up cron jobs. . .${ILRESTORE}"
crontab -l > $HOME/pkg_bkups/backups/cron-jobs.txt
sleep 1

echo
echo "${ILCOLOR2}Updating local git repos. . .${ILRESTORE}"
$HOME/scripts/git-update
sleep 1

echo
echo "${ILCOLOR1}All done. Check for errors. . .${ILRESTORE}"
sleep 1

echo -e ${ILCOLOR2}
echo $(date +%m-%d-%Y) $(date +"%r")
tm_wh_end=$(date +"%s")
		tm_wh_diff=$(( $tm_wh_end - $tm_wh_start))
		echo
		echo "${ILCOLOR2}It took $((($tm_wh_diff % 3600) / 60)) minutes $(($tm_wh_diff % 60)) seconds to run whole process.${ILRESTORE}"
echo -e ${ILRESTORE}
sleep 1
