#!/bin/bash
# http://inglorion.net/software/detach/
# Put your code below this line.
echo 'spike' | sudo -S -v
echo
echo "Checking dependancies. . ."
sleep 1
if dpkg --get-selections | awk '{print $1}' | grep -x "make"; then
	MAKEY="y"
else
	if sudo apt -y install make; then
		MAKEY="y"
	fi
fi
if dpkg --get-selections | awk '{print $1}' | grep -x "cmake"; then
	CMAKEY="y"
else
	if sudo apt -y install cmake; then
		CMAKEY="y"
	fi
fi

if [[ $MAKEY = "y" ]] && [[ $CMAKEY = "y" ]]; then
echo "Now installing 'detach'. . ."
echo "cd $HOME/'Modules-Apps'"
cd $HOME/'Modules-Apps'
sleep 1

echo
echo "cd detach-0.2.3"
cd detach-0.2.3
sleep 1

echo
echo "make"
make
sleep 1

echo
echo "sudo make install"
sudo make install
sleep 1

echo
echo "Done."
else
	echo "Dependencies not installed. Need make and cmake to install detach. Try installing manually: sudo apt make cmake"
fi
