#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo
echo "Setting up custom display size using cvt and xrandr"
echo
sleep 1

# Create variables
XPROF="$HOME/.xprofile"
AUTSTRT="$HOME/.config/autostart/display-start"

# Clean up
rm -rf $XPROF
rm -rf $AUTSTRT

read -p "What display size would you like(width height) ex. 1752 985? " DISP_SIZE

# Setup xrandr properties for custom display and write to .xprofile
RES="$DISP_SIZE"
DISP=$(xrandr | grep -e " connected [^(]" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
MODELINE=$(cvt $(echo $RES) | grep -e "Modeline [^(]" | sed -r 's/.*Modeline (.*)/\1/')
MODERES=$(echo $MODELINE | grep -o -P '(?<=").*(?=")')

# Check for .xprofile file and create and make executable
if [[ ! -f $XPROF ]]; then
	touch $XPROF
	chmod +x $XPROF
fi
cat > $XPROF << _EOF
#!/bin/sh
xrandr --newmode $MODELINE
xrandr --addmode $DISP $MODERES
xrandr -s $MODERES
xrandr --output $DISP --mode $MODERES
_EOF

# Run .xprofile
$XPROF

# Check for .config/autostart file and create and make executable
if [[ ! -f $AUTSTRT ]]; then
	touch $AUTSTRT
	chmod +x $AUTSTRT
fi

# Write .xprofile to execute on startup
echo "#!/bin/bash" > $AUTSTRT
echo "$XPROF" >> $AUTSTRT
