#!/bin/bash
echo
echo "We are setting up dolphin file manager to open a directory in root by using krusader and adding it to menu."
sleep 1

echo
echo "Checking if krusader is installed. . ."
if ! dpkg --get-selections | grep -w "krusader"; then
	sudo -y apt install krusader
else
	echo
	echo "krusader found!"
fi
sleep 2

DIR1="$HOME/.local/share/kservices5"
DIR2="$HOME/.local/share/kservices5/ServiceMenus"
FILE1="$HOME/.local/share/kservices5/ServiceMenus/filemanager_root.desktop"

echo
echo "Checking for and/or creating directories and file. . ."
if [[ ! -d "$DIR1" ]]; then
	mkdir $DIR1
fi
if [[ ! -d "$DIR2" ]]; then
	mkdir $DIR2
fi
if [[ ! -f "$FILE1" ]]; then
    touch $FILE1
fi
sleep 1

echo "" > $FILE1
cat > $FILE1 << _EOF
[Desktop Action root]
# To run actual Dolphin as root
#Exec=/usr/bin/pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true dolphin

# To run Krusader as root (said to be safer)
Exec=/usr/bin/konsole -e sudo krusader
Icon=dolphin
Name=Open in Krusader as root

[Desktop Entry]
Actions=root
Icon=krusader_root
MimeType=inode/directory
ServiceTypes=KonqPopupMenu/Plugin
Type=Service
X-KDE-Priority=TopLevel
X-KDE-StartupNotify=false
_EOF
sleep 2
# This checks exit status for error from output.
if [ $? -eq 0 ]; then
	echo
	echo "${ILCOLOR3}All is good.${ILRESTORE}"
	sleep 1
else
	echo
	echo "${ILCOLOR2}Something went wrong!!!${ILRESTORE}"
	sleep 1
fi
