#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo
echo "Launching EVE online. . ."
echo
sleep 1
ps ax | egrep "*.exe|*exe]" | awk '{ print $1 }' | xargs kill -9
cd ~/.wine32/drive_c/EVE/ && WINEPREFIX=~/.wine32 WINEARCH=win32 wine eve.exe
cd $HOME
