#!/bin/bash
# This generates a bootable linux iso correctly with iso options.
# Put your code below this line.
echo
echo "Checking dependencies. . ."
sleep 1
if ! dpkg --get-selections | grep "genisoimage"; then
	echo
	echo "Package genisoimage not found, installing now. . ."
	sudo apt install genisoimage
	sleep 1
else
	echo
	echo "Package genisoimage is installed. Continuing. . ."
	sleep 1
fi
function iso_gen(){
	echo
	read -p "What is the path of the folder you want to turn into an iso image?: " ISO_NM
	sleep 1
	ISO_NM_OR=$ISO_NM
	echo
	read -p "Type a custom name to add to the beginning of the file or leave blank. " CST_NM
	CST_NM="$CST_NM"$(basename $ISO_NM)
	FRST_NM=$(echo $ISO_NM | sed "s:$(basename $ISO_NM)::g")
	TTL_NM=$(echo $FRST_NM$CST_NM)
	echo $TTL_NM
	sleep 1

	echo
	read -p "The name of the .iso file is to be ${ILCOLOR4}\"$TTL_NM.iso\"${ILRESTORE}. Is that correct? " CRRCT
	sleep 1

	ISO_NM="$TTL_NM.iso"
	if [[ $CRRCT =~ ^([yY][eE][sS]|[yY])$ ]]; then
		ISO_PTH=$(echo $ISO_NM | sed 's:.iso::g')

		echo
		read -p "Running ${ILCOLOR4}\"genisoimage -o $ISO_NM -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -J -R -V -D $ISO_NM_OR\"${ILRESTORE}
Ready to run?: " RDY
		sleep 1
		if [[ $RDY =~ ^([yY][eE][sS]|[yY])$ ]]; then
			sleep 1
			if genisoimage -o $ISO_NM -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -J -R -V -D $ISO_NM_OR; then
				echo
				echo "Iso image ${ILCOLOR4}\"$ISO_NM\"${ILRESTORE} created."
				sleep 1
			else
				echo
				echo "Errors detected."
				sleep 1
			fi
		else
			echo
			echo "Try again. . ."
			sleep 1
			iso_gen
		fi
	else
		echo
		echo "Try again. . ."
		sleep 1
		iso_gen
	fi
}
iso_gen

