#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo "${ILCOLOR2}We will now update your personal git directories consisting of Documents, scripts, etc. . .${ILRESTORE}"
sleep 2

echo "${ILCOLOR1}Updating Projects. . .${ILRESTORE}"
cd ~/Projects
git add --all
git commit -m 'auto commit'
git push -u origin master
sleep 1

echo
echo "${ILCOLOR1}Updating Documents. . .${ILRESTORE}"
cd ~/Documents
git add --all
git commit -m 'auto commit'
git push -u origin master
sleep 1

echo
echo "${ILCOLOR1}Updating scripts. . .${ILRESTORE}"
cd ~/scripts
git add --all
git commit -m 'auto commit'
git push -u origin master
sleep 1

echo
echo "${ILCOLOR1}Updating pkg_bkups. . .${ILRESTORE}"
cd ~/pkg_bkups
git add --all
git commit -m 'auto commit'
git push -u origin master
sleep 1

echo
echo "${ILCOLOR1}Updating Modules-Apps. . .${ILRESTORE}"
cd ~/Modules-Apps
git add --all
git commit -m 'auto commit'
git push -u origin master
sleep 1

echo
echo "${ILCOLOR1}Updating MSI_live-build. . .${ILRESTORE}"
cd ~/MSI_live-build
git add --all
git commit -m 'auto commit'
git push -u origin master
sleep 1

echo
echo "${ILCOLOR1}Dowloading usb_pkg_bkups. . .${ILRESTORE}"
cd ~/usb_pkg_bkups
git stash
git fetch
git pull
sleep 1

cd $HOME
