#!/bin/sh
# This is a bash script.
# Put your description below this line and code below that.
#
cd /
echo
echo "Installing latest Google Chrome..."
sleep 3

for usrs in $(ls /home | sed 's:lost+found::g'); do
	HOME_DIR="/home/$usrs"
echo
echo "Cleaning downloads folder of other chrome files..."
if [ ! -d "$HOME_DIR/Downloads" ]; then
	mkdir -p "$HOME_DIR/Downloads"
fi
cd $HOME_DIR/Downloads
sleep 1
if [ -f google-chrome*.* ]; then
	rm -rf google-chrome*.*
fi
sleep 2

echo
echo "Downloading latest Google Chrome..."
sleep 1
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sleep 2

echo
echo "Installing latest Google Chrome..."
sleep 1
sudo dpkg -i google-chrome*.*
sleep 2
done

echo
echo "Done!"
cd /
sleep 3
