#!/bin/sh
# This is a bash script.
# Put your description below this line and code below that.
# 
echo
echo "Installing latest Google Chrome..."
sleep 3

echo
echo "Cleaning downloads folder of other chrome files..."
if [ ! -d "$HOME/Downloads" ]; then
	mkdir -p "$HOME/Downloads"
fi
cd $HOME/Downloads
sleep 1
if [ -f google-chrome*.* ]; then
	rm -rf google-chrome*.*
fi
sleep 2

echo
echo "Downloading latest Google Chrome..."
sleep 1
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sleep 2

echo
echo "Installing latest Google Chrome..."
sleep 1
sudo dpkg -i google-chrome*.*
sleep 2

echo
echo "Done!"
cd $HOME
sleep 3
