#!/bin/bash
# This is a bash script.
# Put your description below this line and code below that.
# 
echo "spike" | sudo -S -v
echo
echo "${ILCOLOR3}This will install the kali-rolling repo to your system."
sleep 1

YEAR=$(date +"%Y")
SOURCES="/etc/apt/sources.list"
KALI_ADDR="https://http.kali.org/kali/pool/main/k/kali-archive-keyring/"
KALI_FILE="kali-archive-keyring_$YEAR.1_all.deb"

echo
echo "${ILCOLOR3}Adding repos to${ILRESTORE} $SOURCES. . ."
echo
sleep 1
# Removing all white space from end of file.
sudo sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' $SOURCES
echo -e "\n" | sudo tee -a $SOURCES
echo "${ILCOLOR3}echo${ILRESTORE} ###Kali linux repos(for hacking tools) | sudo tee -a $SOURCES"
echo "###Kali linux repos(for hacking tools)" | sudo tee -a $SOURCES
echo
sleep 3
echo "${ILCOLOR3}echo${ILRESTORE} deb [signed-by=/usr/share/keyrings/kali-archive-keyring.gpg] http://http.kali.org/kali/ kali-rolling main non-free contrib | sudo tee -a $SOURCES"
echo "deb [signed-by=/usr/share/keyrings/kali-archive-keyring.gpg] http://http.kali.org/kali/ kali-rolling main non-free contrib" | sudo tee -a $SOURCES
echo
sleep 3
echo "${ILCOLOR3}echo${ILRESTORE} deb-src [signed-by=/usr/share/keyrings/kali-archive-keyring.gpg] http://http.kali.org/kali/ kali-rolling main non-free contrib | sudo tee -a $SOURCES"
echo "deb-src [signed-by=/usr/share/keyrings/kali-archive-keyring.gpg] http://http.kali.org/kali/ kali-rolling main non-free contrib" | sudo tee -a $SOURCES
echo
sleep 3

echo
echo "${ILCOLOR3}Adding trusted key to /usr/share/keyrings. . .${ILRESTORE}"
sleep 1

echo "${ILCOLOR3}Getting file${ILRESTORE} $KALI_ADDR$KALI_FILE. . ."
sleep 1
if [[ ! -d "$HOME/Downloads" ]]; then
	mkdir "$HOME/Downloads"
fi
cd $HOME/Downloads
wget $KALI_ADDR$KALI_FILE

echo "${ILCOLOR3}Installing $KALI_FILE${ILRESTORE}"
sudo dpkg -i $HOME/Downloads/$KALI_FILE
