#!/bin/bash
# Setting up auto login and numlock on system startup
# Check if script has been run as root.
if [[ ! "$USER" = "root" ]]; then
	echo "This script must be run as root!"
	exit
fi

# Set up varible.
CONF="/etc/lightdm/lightdm.conf"

# Script explains what it's doing.
echo
echo "${ILCOLOR3}Setting up lightdm, auto-login and auto numlock. . .${ILRESTORE}"
sleep 1
echo
if dpkg --get-selections | awk '{print $1}' | grep -wq "lightdm"; then
	sleep 1
	echo
	echo "Lightdm is already installed."
else
	sleep
	echo
	echo "Lightdm not installed, installing now. . ."
	sudo apt -y install lightdm
fi

echo
sleep 1
echo "${ILCOLOR3}Editing file $CONF. Umcommenting and adding user file.${ILRESTORE}"
echo
sleep 1

# Check for file and create if necessary
if [[ ! -f $CONF ]]; then
	echo
	echo "File $CONF not found, creating now. . . "
	sleep 1
	touch $CONF
	echo "[SeatDefaults]" > $CONF
fi

# Check if '[SeatDefaults]' flag is in file.
echo
echo "Checking for flag '[SeatDefaults]' in $CONF. . ."
if ! grep -wq "SeatDefaults" $CONF; then
	echo "[SeatDefaults]" > $CONF
	echo "Added [SeatDefaults] to $CONF"
	sleep 1
else
	echo "Flag '[SeatDefaults]' found."
	sleep 1
fi

# Check if phrase exists, is commented out, and if so uncommenting, if not then letting us know it's already updated.
echo
echo "Checking for autologin-user=msifland. . ."
if ! grep -wq "autologin-user" $CONF; then
		echo "autologin-user=msifland" >> $CONF
		echo "Added to $CONF"
		sleep 1
elif grep -q "^#autologin-user="  $CONF; then
	sed -i 's:#autologin-user=.*:autologin-user=msifland:g' $CONF
	echo "Uncommented in $CONF"
	sleep 1
else
	echo "Already updated autologin-user."
	sleep 1
fi

# Check if phrase is commented out, and if so uncommenting, if not then letting us know it's already updated.
echo
echo "Checking for autologin-user-timeout=0. . ."
if ! grep -wq "autologin-user-timeout" $CONF; then
	echo "autologin-user-timeout=0" >> $CONF
	echo "Added to $CONF"
	sleep 1
elif grep -q "^#autologin-user-timeout=0"  $CONF; then
	sed -i 's:#autologin-user-timeout=0:autologin-user-timeout=0:g' $CONF
	echo "Uncommented from $CONF"
	sleep 1
else
	echo "Already updated autologin-user-timeout."
	sleep 1
fi

# For numlock on, we need an application name numlockx installed. Checking if installed, if not, then install it. Then look for needed phrase, if not there then add it to bottom of file.
if dpkg --get-selections | awk '{print $1}' | grep -wq "numlockx"; then
	if grep -wq "greeter-setup-script=/usr/bin/numlockx on" $CONF; then
		echo
		echo "Numlockx on already added."
		sleep 1
	else
		echo
		echo "Adding numlock on at startup. . ."
		echo "greeter-setup-script=/usr/bin/numlockx on" >> $CONF
		sleep 1
	fi
else
	echo
	echo "Installing numlockx. . ."
	sleep 1
	sudo apt -y install numlockx
	if grep -wq "greeter-setup-script=/usr/bin/numlockx on" $CONF; then
		echo
		echo "numlockx on already added."
		sleep 1
	else
		echo
		echo "Adding numlock on at startup. . ."
		echo "greeter-setup-script=/usr/bin/numlockx on" >> $CONF
		sleep 1
	fi
fi
sudo systemctl enable lightdm
sudo systemclt start lightdm

echo
echo "Rebooting now. . ."
sleep 5
sudo reboot
