#!/bin/bash
# Put this script in $HOME/.config/autostart by add a starup app, or converting to a .desktop app, on linux-usb installation.
#This scripts updates git repos when the device starts. 
#
if ! dpkg --get-selections | awk '{print $1}' | grep -xq "xterm"; then
	sudo apt install xterm
fi
/usr/bin/xterm -e "bash -c \"source ~/.bashrc; clear
echo Running update git repos to this system. . .
sleep 2
echo $HOME/pkg_bkups
cd $HOME/pkg_bkups
git stash
git fetch
git pull
sleep 1
echo
echo $HOME/scripts
cd $HOME/scripts
git stash
git fetch
git pull
sleep 1
echo
echo $HOME/Documents
cd $HOME/Documents
git stash
git fetch
git pull
sleep 1
echo
echo $HOME/Projects
cd $HOME/Projects
git stash
git fetch
git pull
sleep 1
echo
echo $HOME/Modules-Apps
cd $HOME/Modules-Apps
git stash
git fetch
git pull
sleep 1
echo
cd\""

sleep 3
$HOME/scripts/linux-usb-update
