#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.

# Checking for root first.
if [[ "$USER" != 'root' ]]; then
	echo "This must be run as root!!!"
	exit
fi

# Telling what we are doing.
echo
echo "Upating mate-panel to make so it delays before starting for icon placement bug. . ."
echo
sleep 1

# Check to see if update has already been done so we don't copy the file again.
if grep -Fxq "sleep 30; mate-panel-later" /usr/bin/mate-panel; then
	echo "Already updated."
	echo
	if [[ $HOME/tmp/mate-panel.bk ]]; then
		rm $HOME/tmp/mate-panel.bk
	fi
	sleep 1
	exit
fi

# Rename curretn app that the system calls and creating a new one to delay the call of the first one.
cp /usr/bin/mate-panel $HOME/tmp/mate-panel.bk; mv /usr/bin/mate-panel /usr/bin/mate-panel-later
touch /usr/bin/mate-panel
chmod 755 /usr/bin/mate-panel
echo "sleep 30; mate-panel-later" > /usr/bin/mate-panel
sleep 1

# Check for errors and report.
if [ $? -eq 0 ]; then
	echo "All went well."
else
	echo "Error detected. Better check it out."
fi
echo
rm $HOME/tmp/mate-panel.bk
sleep 1

exit
