#!/bin/bash

color="\033[0;38;5;$((RANDOM % 255+1))m"
#'\e[1;32;05;219m'
color2="\033[4;38;5;$((RANDOM % 255+1))m"
#'\033[1;38;5;027m'
color3="\033[0;38;5;$((RANDOM % 255+1))m"
restore='\033[0m'

# Showing aliases
echo -e "${color2}"
echo "my-aliases"
echo "${ILRESTORE}${ILCOLOR1}/home/msifland/.bashrc"
echo -e "${color}"
grep -i 'alias ' $HOME/.bashrc | sed "s/alias //g" | sed "s/my-aliases//g" | sed "s/\\t//g" | sort |    pv -qL 3000
echo

# This part of my functions actually showing the functions listed in the .bashrc file.
echo -e "${color2}"
echo "my-functions"
echo "${ILRESTORE}${ILCOLOR1}/home/msifland/.bashrc"
echo -e "${color}"
# Removing items to show in list.
grep -i 'function ' $HOME/.bashrc | sed 's#function goto(){##g' | sed "s/function //g" | sed "s/(){//g" | sed "s/my-functions//g" | sort | sed '/^\s*$/d' |    pv -qL 3000
echo

# Showing scripts and rom_scripts
echo -e "${color2}"
echo "script files"
echo "${ILRESTORE}${ILCOLOR1}/home/msifland/scripts"
echo -e "${color}"
find $HOME/scripts -maxdepth 1 -type f | sed 's#/home/msifland/scripts/##' | sed 's#README.md##' | sed 's#restart_log.txt##' | sed '/^$/d' | sort |    pv -qL 2000
echo

# Kernel scripts
echo -e "${color2}"
echo "kernel script files"
echo "${ILRESTORE}${ILCOLOR1}/home/msifland/scripts/kernel_scripts"
echo -e "${color}"
find $HOME/scripts/kernel_scripts -maxdepth 1 -type f | sed 's:/home/msifland/scripts/kernel_scripts/::g' | sed 's:kern-update-timer::g' | sed '/^$/d' | sort |    pv -qL 2000
echo
echo
exit

