#!/bin/bash

color="\033[0;38;5;$((RANDOM % 255+1))m"
#'\e[1;32;05;219m'
color2="\033[4;38;5;$((RANDOM % 255+1))m"
#'\033[1;38;5;027m'
restore='\033[0m'

# First part of my functions actually showing the functions listed in the .zshrc file.
echo -e "${color2}"; echo "my-functions"
echo -e "${color}"
# Removing items to show in list.
grep -i 'function ' $HOME/.zshrc | sed 's#function goto(){##g' | sed "s/function //g" | sed "s/(){//g" | sed "s/my-functions//g" | sort

# Second part showing aliases
echo -e "${color2}"; echo "my-aliases"; 
echo -e "${color}"
grep -i 'alias ' $HOME/.zshrc | sed "s/alias //g" | sed "s/my-aliases//g" | sed "s/\\t//g" | sort
echo

# Third part showing scripts and rom_scripts
echo -e "${color2}"
echo "script files"
echo -e "${color}"
find $HOME/scripts -maxdepth 1 -type f | sed 's#/home/msifland/scripts/##' | sed 's#README.md##' | sed 's#restart_log.txt##' | sed '/^$/d' | sort
echo

echo -e "${color2}"
echo "rom script files"
echo -e "${color}"
find $HOME/rom_scripts -maxdepth 1 -type f | sed 's#/home/msifland/rom_scripts/##' | sed 's#README.md##' | sed 's#restart_log.txt##' | sed '/^$/d' | sort
echo
echo
exit

