#!/bin/bash
# This scripts counts how many packages you have installed and shows them on screen with a count.
if [[ "$1" = "" ]]; then
echo
# Get list of packages.
PKGS=$(dpkg --get-selections | awk '{print $1}')

# Set variable n to start count then loop and add 1 for counting. Echo all packages on screen with count, then tell total number of apps.
n=0
for i in $PKGS; do
	let n=$n+1
	echo "${ILRESTORE}$n. ${ILCOLOR3}$i"
done
echo
echo "${ILCOLOR4}You currently have ${ILCOLOR3}$n ${ILCOLOR4}applications installed on your system.${ILRESTORE}" | pv -qL 80
echo
sleep 1
else
	PKGS=$(dpkg --get-selections | awk '{print $1}' | grep "$1")
	n=0
	for i in $PKGS; do
		let n=$n+1
		echo "${ILRESTORE}$n. ${ILCOLOR3}$i" | pv -qL 800
	done
	echo
	echo "${ILCOLOR4}There are ${ILCOLOR3}$n ${ILCOLOR4}applications that match ${ILCOLOR3}$1.${ILRESTORE}" | pv -qL 80
	echo
	sleep 1
fi
echo "${ILRESTORE}Usage: 'packages' lists all install packages on system.
       'packages linux' lists all install packages that match the word 'linux'."
