#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo
echo "${ILCOLOR1}Listing all ppa's installed on system. . .${ILRESTORE}"
echo
sleep 1

for APT in `find /etc/apt/ -name \*.list`; do
    grep -Po "(?<=^deb\s).*?(?=#|$)" $APT | while read ENTRY ; do
        HOST=`echo $ENTRY | cut -d/ -f3`        
        USER=`echo $ENTRY | cut -d/ -f4`        
        PPA=`echo $ENTRY | cut -d/ -f5`
        
        #echo sudo apt-add-repository ppa:$USER/$PPA    
        if [ "ppa.launchpad.net" = "$HOST" ]; then
            echo $USER/$PPA
        else
            echo \'${ENTRY}\'
        fi
    done
done
exit
#sudo apt-add-repository ppa:
#sudo apt-add-repository 