#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
qemu-system-x86_64 \
  -m 4G \
  -enable-kvm \
  -cpu host \
  -drive file=/dev/sdb,format=raw,if=virtio \
  -boot menu=on
