#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
if [[ ! -z $1 ]]; then
    qemu-system-x86_64 \
    -m 4G \
    -enable-kvm \
    -cpu host \
    -drive file=$1,format=raw,if=virtio \
    -boot menu=on
else
    echo "
    This command runs qemu virtal box.
    Usage:
    qemu-run [full directory]
    qemu-run ~/live-build/MY_live-debian.iso
    qemu-run /home/msifland/iso/Debian-14-1.iso
    sudo qemu-run /dev/sdb
    sudo qemu-run /dev/sda"
fi
