#!/bin/bash
# This is a quick script to reinstall all currently install packages.
echo
echo "${ILCOLOR1}Reinstalling all installed apps. . ."
echo
sleep 1

echo
yn_proc="n"
read -p "Are you ready to proceed[y/N]?: " yn_proc
sleep 1

if [[ "$yn_proc" =~ ^([yY][eE][sS]|[yY])$ ]]; then
	if for pkg in $(dpkg --get-selections | awk '{print $1}' | egrep -v '(dpkg|apt|mysql|mythtv)'); do sudo apt install -y -f --reinstall $pkg; done; then
		echo
		echo "${ILCOLOR3}*******Error detected!!!*******"
		sleep 1
	else
		echo "${ILCOLOR2}Clean install."
	fi
else
	echo
	echo "${ILCOLOR2}Exiting now."
	sleep 1
	exit
fi

