#!/bin/bash
# This scripts adds sources to /etc/apt/sources.list

# Checking for root and re-run under root if not.
if [[ "$EUID" -ne "0" ]]; then
	echo
	echo "${ILCOLOR3}This scripts has to be run as superuser."
	echo "You will be prompted for password for superuser. Enter password, and scripts will re-run as superuser. It may ask for password more than once.${ILRESTORE}"
	sleep 1
	echo "su"
	su - "root" -c "/home/msifland/scripts/sources-add && exit" && echo && echo "Enter root password to exit" && su - "msifland" -c exit
	exit
else
	echo
	echo "Ok proceeding as root. . ."
	sleep 1
fi

# Used function for loop recall.
function add_sources(){
	# Removing all white space from end of file.
	echo "$(awk '/^$/ {nlstack=nlstack "\n";next;} {printf "%s",nlstack; nlstack=""; print;}' /etc/apt/sources.list)" > /etc/apt/sources.list

	# Asking for source to add and double checking that it's correct. If it's not, then loop to beginning. Also option to exit.
	echo
	read -p "Adding source to /etc/apt/sources.list. Enter source to add and make sure it starts with \"deb \", if not, add \"deb <source>\" : " srcs
	echo
	read -p "You have chosen to add \"$srcs\" to your sources.list. Is it correct? " yn_src
	if [[ ! "$yn_src" =~ ^([yY][eE][sS]|[yY])$ ]]; then
		echo
		read -p "Try again? " ta
		if [[ "$ta" =~ ^([nN][oO]|[nN])$ ]]; then
			echo
			echo "Ok, exiting. . ."
			sleep 1
			exit
		else
			echo
			echo "Trying again. . ."
			sleep 1
			add_sources
		fi
	else
		sleep 1

		# Here we are echoing the command that we are going to execute to add to the file.
		echo
		echo "echo \"$srcs\" | sudo tee -a /etc/apt/sources.list"
		sleep 1

		# Need to add three lines here. One with a 'Added manually' tag, one with the source, one with the source and 'deb-src' at the beginning. The 'echo -e' makes echo execute the '\n' which is newline.
		# Checking for errors here and reporting if there are.
		if echo -e "\n#Added manually\n$srcs\ndeb-src $srcs" | sudo tee -a /etc/apt/sources.list; then
			echo
			echo "\"$srcs\" has been added to your sources.list."
		else
			echo
			echo "Problem detected. Add manually."
		fi
	fi

	# Reformatting sources file due to 'deb-src' second line.
	sudo sed -i 's:deb-src deb:deb-src:g' /etc/apt/sources.list
}

# Main function call.
add_sources

# Opening file for double checking and manual editing.
echo
echo "Showing /etc/apt/sources.list for manual edit if needed."
sleep 2
sudo nano /etc/apt/sources.list
