#!/bin/bash
# This scripts adds sources to /etc/apt/sources.list

# Used function for loop purposes.
function add_sources(){
	
	# Asking for source to add and double checking that it's correct. If it's not, then loop to beginning. Also option to exit.
	echo
	read -p "Adding source to /etc/apt/sources.list. Enter source to add and make sure it starts with \"deb \", if not, add \"deb <source>\" : " srcs
	echo
	read -p "You have chosen to add \"$srcs\" to your sources.list. Is it correct? " yn_src
	if [[ ! "$yn_src" =~ ^([yY][eE][sS]|[yY])$ ]]; then
		echo
		read -p "Try again? " ta
		if [[ "$ta" =~ ^([nN][oO]|[nN])$ ]]; then
			echo
			echo "Ok, exiting. . ."
			sleep 1
			exit
		else
			echo
			echo "Trying again. . ."
			sleep 1
			add_sources
		fi
	else
		sleep 1

		# Here we are echoing the command that we are going to execute to add to the file.
		echo
		echo "echo \"$srcs\" | sudo tee -a /etc/apt/sources.list"
		sleep 1

		# Need to add three lines here. One with a 'Added manually' tag, one with the source, one with the source and 'deb-src' at the beginning. The 'echo -e' makes echo execute the '\n' which is newline.
		# Checking for errors here and reporting if there are.
		if echo -e "\n#Added manually\n$srcs\ndeb-src $srcs" | sudo tee -a /etc/apt/sources.list; then
			echo
			echo "\"$srcs\" has been added to your sources.list."
		else
			echo
			echo "Problem detected. Add manually."
		fi
	fi

	# Reformatting sources file due to 'deb-src' second line.
	sudo sed -i 's:deb-src deb:deb-src:g' /etc/apt/sources.list
}

# Main function call.
add_sources

# On some systems 'gawk' is not installed automatically. This checks to see if it's installed, if not, then install it.
# Removing all white space from end of file.
if dpkg --get-selections | awk '{print $1}' | grep -wq "gawk"; then
    sudo gawk -i inplace '/^$/ {nlstack=nlstack "\n";next;} {printf "%s",nlstack; nlstack=""; print;}' /etc/apt/sources.list
else
    sudo apt -y install gawk
    sudo gawk -i inplace '/^$/ {nlstack=nlstack "\n";next;} {printf "%s",nlstack; nlstack=""; print;}' /etc/apt/sources.list
fi

# Opening file for double checking and manual editing.
echo
echo "Showing /etc/apt/sources.list for manual edit if needed."
sleep 2
sudo nano /etc/apt/sources.list
