#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo 'spike' | sudo -S -v

sudo umount /mnt/ubuntu
sudo rm -rf /mnt/ubuntu
echo
echo "This is going to install Ubuntu to a drive or partition of your choice. It will be installed under one file system and partiton."
sleep 1

echo
echo "Here are the available drives:"
sleep 1

echo
lsblk
sleep 1

echo
read -p "Please type drive that you would like to install ubunut too(ex. /dev/sda1, /dev/sdb 2, etc.) " INST_DRV

echo
read -p "We are going to format drive to ext4, which will erase all datat on $INST_DRV. Are you sure you want to proceed[y/N]? " PR_YN
if [[ ! "$PR_YN" =~ ^([Yy][Ee][Ss]|[Yy])$ ]]; then
	echo
	echo "Not proceeding and exiting. . ."
	sleep 1
	exit
else
	echo
	echo "Ok, proceeding to format $INST_DRV. . ."
	sudo mkfs -t ext4 $INST_DRV
	sleep 1
fi

sudo mkdir /mnt/ubuntu
sudo mount $INST_DRV /mnt/ubuntu

echo
echo "Checking to make sure debootstrap is installed. . ."
if ! dpkg --get-selections | awk '{print $ 1}' | grep -wq "debootstrap"; then
	sudo apt -y install debootstrap
else
	echo
	echo "debootstrap is present, proceeding. . ."
fi
sleep 1

echo
read -p "right-click this link: https://wiki.ubuntu.com/Releases, and open link to find the name variant you want to install(ex. bionic, disco, trusty, etc.). Type lowercase name variant here: " NM_VAR
sleep 1

echo
echo "Installing now for 64bit systems. . ."
sleep 1
sudo debootstrap --arch amd64 $NM_VAR /mnt/ubuntu http://archive.ubuntu.com/ubuntu

echo
echo "Chroot'ing into newly installed environment. . ."
sleep 1

echo
sudo mount -o bind /dev /mnt/ubuntu/dev
sudo mount -o bind /dev/pts /mnt/ubuntu/dev/pts
sudo mount -t proc /proc /mnt/ubuntu/proc
sudo mount -t sysfs /sys /mnt/ubuntu/sys
sudo rm -rf /mnt/ubuntu/etc/apt/sources.list
sudo cp /etc/apt/sources.list /mnt/ubuntu/etc/apt/
sudo cp /etc/resolv.conf /mnt/ubuntu/etc/resolv.conf
sudo cp /etc/hosts /mnt/ubuntu/etc/hosts
sudo cp /usr/share/zoneinfo/America/Chicago /mnt/ubuntu/etc/localtime

sudo cp $HOME/scripts/ubuntu-install-deps /mnt/ubuntu/
sudo NM_VAR="$NM_VAR" INST_DRV="$INST_DRV" chroot /mnt/ubuntu /bin/bash -c "./ubuntu-install-deps"

sudo rm -rf /mnt/ubuntu/etc/network/interfaces
sudo cp /etc/network/interfaces $HOME/tmp/
WI_AD=$(ifconfig | awk '{print $1}' | grep "^e" | sed 's/://g' | sed '/ether/d')
echo "allow-hotplug $WI_AD" >> $HOME/tmp/interfaces
echo "iface $WI_AD inet dhcp" >> $HOME/tmp/interfaces
ETH_AD=$(ifconfig | awk '{print $1}' | grep "^w" | sed 's/://g')
echo "allow-hotplug $ETH_AD" >> $HOME/tmp/interfaces
echo "iface $ETH_AD inet dhcp" >> $HOME/tmp/interfaces
sudo cp $HOME/tmp/interfaces /mnt/ubuntu/etc/network/interfaces
echo
echo "Run update-grub if you haven't already in the install."
echo "Restart and install other apps. But, first, on restart run: sudo tasksel install standard."
sleep 1
sudo rm -rf /mnt/ubuntu/ubuntu-install-deps
sudo umount /mnt/ubuntu/dev/pts
sudo umount /mnt/ubuntu/dev
sudo umount /mnt/ubuntu/proc
sudo umount /mnt/ubuntu/sys
sudo umount /mnt/ubuntu

echo
exit
