#!/bin/bash
# This is a scripts that solves scrambles letters to words.
WORD_FILE="$HOME/Documents/my-english-words.txt"

echo
read -p "${ILCOLOR2}Enter the letters to unscramble:${ILRESTORE} " ltrs
echo
sleep 1

LTRS_NMBR=$(echo -n "$ltrs" | wc -c)

echo "${ILCOLOR3}Showing words with only $LTRS_NMBR letters first.${ILRESTORE}"
sleep 1
grep -E -i "^[$ltrs]{$LTRS_NMBR}$" $WORD_FILE | column

echo
read -p "${ILCOLOR3}Press [ENTER] to show all words with these letters in them.${ILRESTORE}"
grep -E -i "^[$ltrs]*$" $WORD_FILE | awk '{ print length(), $0 | "sort -n" }' | column

