#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
# Find out if process is running. If it is assign the PID of the process to a variable. Then shut down the process with a loop.
echo
echo "Making sure conky is not running..."
sleep 1
cpid=$(pidof conky)
while [[ $cpid != "" ]]; do
	echo "Shutting down conky. . ."
	echo "PID="$cpid
	cpid=$(pidof conky)
	killall conky
	sleep 1
done

echo
echo 'Starting conky in:'
# Start a countdown to action.
secs=$((2 * 30))
while [ $secs -gt 0 ]; do
   echo -ne "$secs\033[0K\r"
   sleep 1
   : $((secs--))
done

# Start conky
echo "Starting conky now. . ."
conky
sleep 10
# Kill current terminal that this process is running in.
kill -9 $PPID
