#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
echo
echo

# Set variables.
SYNC_DIR="$HOME/Dropbox/Android/aicp"
# Here we need a certain date format for search the website.
DATE="$(date +%F | sed 's:-::g').zip.html"
# Search website for current changelog based on date.
GET=$(wget -qO- http://dwnld.aicp-rom.com/\?device\=marlin | grep $DATE)

# Here we echo to a file the link address. The reason is that assigning varialbel with $() or `` outputs an error because of a &nbsp in the sed command. Sed is removing all the blabbaer and jsut returing the address to the link.
echo $GET | sed 's:&nbsp; <b>Change Log </b>\: <a href="::g' | sed 's#">aicp_marlin_o-13.1-NIGHTLY-'$DATE'</a><br/></a>##g' > $HOME/tmp/aicp.txt

# Pull the link address from the file we just made and assign to variable.
LINK=$(< $HOME/tmp/aicp.txt)
# Variable assigned, file no longer needed.
rm $HOME/tmp/aicp.txt

# Check if directory exists.
if [[ ! -d $SYNC_DIR ]]; then
	mkdir $SYNC_DIR
fi

# Change to dirctory to download to and download file.
cd $SYNC_DIR
echo "Getting AICP Changelog: $LINK"
wget $LINK

#Remove files more than five.
ls $SYNC_DIR/* -t | tail -n +6 | xargs rm -f

# Get last file in list and open it.
# ls -cr lists files from oldest to newest.
FILE_TO_OPEN=$(ls -cr | tail -n1)
detach google-chrome-stable $FILE_TO_OPEN

cd $HOME