#!/bin/bash
echo
echo "We are setting up dolphin file manager to have a 'Copy Path' added to menu."
sleep 1

echo
echo "Checking if xclip is installed. . ."
sleep 1
if ! dpkg --get-selections | grep -wq "xclip"; then
	sudo -y apt install xclip
else
	echo
	echo "xclip found!"
fi
sleep 1

DIR1="$HOME/.local/share/kservices5"
DIR2="$HOME/.local/share/kservices5/ServiceMenus"
FILE1="$HOME/.local/share/kservices5/ServiceMenus/copy_path.desktop"

echo
echo "Checking for and/or creating directories and file. . ."
if [[ ! -d "$DIR1" ]]; then
	mkdir $DIR1
fi
if [[ ! -d "$DIR2" ]]; then
	mkdir $DIR2
fi
if [[ ! -f "$FILE1" ]]; then
    touch $FILE1
fi
sleep 1

echo "" > $FILE1
cat > $FILE1 << _EOF
[Desktop Action copy-path]
Exec=echo "%U" | tr -d '\n' | xclip -selection clipboard
Name=Copy Path
Icon=edit-copy

[Desktop Entry]
Actions=copy-path
ServiceTypes=KonqPopupMenu/Plugin
MimeType=all/all
Type=Service
X-KDE-Priority=TopLevel
Exec=echo -n %U | xsel -b 
_EOF
sleep 2
# This checks exit status for error from output.
if [ $? -eq 0 ]; then
	echo
	echo "${ILCOLOR3}All is good.${ILRESTORE}"
	sleep 1
else
	echo
	echo "${ILCOLOR2}Something went wrong!!!${ILRESTORE}"
	sleep 1
fi
