#!/bin/bash
PW="spike"
echo
echo "echo 1 >/proc/sys/vm/drop_caches"
echo $PW | sudo -S sh -c -v 'echo 1 >/proc/sys/vm/drop_caches'
echo "echo 2 >/proc/sys/vm/drop_caches"
echo $PW | sudo -S sh -c -v 'echo 2 >/proc/sys/vm/drop_caches'
echo "echo 3 >/proc/sys/vm/drop_caches"
echo $PW | sudo -S sh -c -v 'echo 3 >/proc/sys/vm/drop_caches'
exit
