#!/bin/bash

cd $HOME/maps

echo
echo "${ILCOLOR1}This scripts allows you to build a custom state map for your garmin device...${ILRESTORE}"
sleep 1

echo
echo -n "What State would you like to build?[state name lower case. two name states get a hyphen] "
read STATE
sleep 1
### Log date and time
DATE_START=$(date +"%s")
echo "Build Start Time:"
DATE=$(date +"%m-%d-%y")
echo "Date: $DATE"
TIME=$(date +"%r")
echo "Time: $TIME"
echo

echo
echo "${ILCOLOR1}Starting process of downloading and building Garmin map of Geofarik maps:${ILRESTORE} "$STATE
sleep 1

if [[ ! -d "$HOME/maps/$STATE" ]]; then
	mkdir "$HOME/maps/$STATE"
fi

if [[ -f "$HOME/maps/$STATE_gmapsupp.img" ]]; then
	rm -rf $HOME/maps/$STATE_gmapsupp.img.old
	mv $HOME/maps/$STATE_gmapsupp.img $HOME/maps/$STATE_gmapsupp.img.old
fi

echo
echo "${ILCOLOR1}Downloading map...${ILRESTORE}"
sleep 1
echo
wget -O $HOME/maps/"$STATE"_latest.osm.pbf http://download.geofabrik.de/north-america/us/$STATE-latest.osm.pbf

echo
echo "${ILCOLOR1}Moving "$STATE"_latest.osm.pbf file to $STATE folder...${ILRESTORE}"
mv "$STATE"_latest.osm.pbf $HOME/maps/$STATE/$STATE.osm.pbf
cd $HOME/maps/$STATE

# Formatting for faster and better processing.
echo
echo "${ILCOLOR1}Converting .pbf file to .o5m for faster formatting using osmconvert...${ILRESTORE}"
sleep 1
osmconvert --drop-version $HOME/maps/$STATE/$STATE.osm.pbf -o=$HOME/maps/$STATE/$STATE.o5m

echo
echo "${ILCOLOR1}Splitting file...${ILRESTORE}"
sleep 1
mkgmap-splitter $HOME/maps/$STATE/$STATE.o5m --max-nodes=800000 --output=xml

echo
echo "${ILCOLOR1}Creating img, this will take a while...${ILRESTORE}"
sleep 1
mkgmap --style-file=$HOME/maps/styles/mine  --family-id=2000 --route --gmapsupp *.osm.gz $HOME/maps/osm_new.typ

echo
echo "${ILCOLOR1}Moving gmapsupp.img to Maps folder and renaming to $STATE_gmapsupp.img...${ILRESTORE}"
sleep 1
mv $HOME/maps/$STATE/gmapsupp.img $HOME/maps/"$STATE"_gmapsupp.img
sleep 1

echo
echo "${ILCOLOR1}Checking for Garmin Device. . .${ILRESTORE}"
sleep 1
if [[ -d "/media/msifland/D216-4B4C" ]]; then
	rsync --progress --verbose $HOME/maps/$STATE_gmapsupp.img /media/msifland/D216-4B4C/Garmin/$STATE_gmapsupp.img
else
	echo
	echo "${ILCOLOR1}No Garmin Device found. Copy manually later.${ILRESTORE}"
fi
sleep 1

echo
echo "${ILCOLOR1}Cleaning up files...${ILRESTORE}"
sleep 1

echo
rm -rf $HOME/maps/$STATE
rm -rf $HOME/maps/*.osm.pbf

echo
echo "${ILCOLOR1}Finished."
sleep 1
echo "Build End Time:"
DATE=$(date +"%m-%d-%y")
echo "Date: $DATE"
TIME=$(date +"%r")
echo "Time: $TIME"
DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
echo "It took $(($DIFF / 3600 )) hours $((($DIFF % 3600) / 60)) minutes $(($DIFF % 60)) seconds to build."
echo -e "${RESTORE}"

cd $HOME
$HOME/scripts/free-ram
exit

#for i in *; do mv "$i" 1_"$i"; done
#rename -N 0001 -X 's/.*/$N/' *.jpg
