#!/bin/bash
# Setting up auto login and numlock on system startup
# Check if script has been run as root.
if [[ ! "$USER" = "root" ]]; then
	echo "This script must be run as root!"
	exit
fi

# Set up varible.
CONF="/etc/sddm.conf"

# Script explains what it's doing.
echo
echo "${ILCOLOR3}Setting auto numlock at login for sddm. . .${ILRESTORE}"
echo
sleep 2

echo "${ILCOLOR3}Creating and editing file $CONF. Adding:
[General]
Numlock=on
${ILRESTORE}"
echo
sleep 2

# Check for file and create if necessary
if [[ ! -f $CONF ]]; then
	echo
	echo "File $CONF not found, creating now. . . "
	sleep 2
	touch $CONF
fi

# Check if '[General]' flag is in file.
echo
echo "Checking for flag '[General]' in $CONF. . ."
if ! grep -wq "General" $CONF; then
	echo "[General]" > $CONF
	echo "Added [General] to $CONF"
	sleep 2
else
	echo "Flag '[General]' found."
	sleep 2
fi

echo
echo "Checking for Numlock=on. . ."
if ! grep -wq "Numlock=on" $CONF; then
	echo "Numlock=on" >> $CONF
	echo "Added to $CONF"
	sleep 2
else
	echo "Already updated Numlock=on."
	sleep 2
fi

# Check for errors and let user know if there were.
if [[ $? -eq 0 ]]; then
	echo
	echo "All is good."
	sleep 2
else
	echo
	echo "Errors were detected. Check file manually."
	sleep 2
fi

# Removing blank lines at end of file.
sed -i '/^$/d' $CONF
echo "$(awk '/^$/ {nlstack=nlstack "\n";next;} {printf "%s",nlstack; nlstack=""; print;}' $CONF)" > $CONF
