#!/bin/bash

# Bash Color Random
COLOR="\033[1;38;5;$((RANDOM % 255+1))m"
RESTORE='\033[0m'

pswd="spike"

function refresh(){
	echo -e "${COLOR}"
	# Log date and time
	DATE_START=$(date +"%s")
	echo "Update Start Time:" | tee $HOME/scripts/keys-refresh.txt
	DATE=$(date +"%m-%d-%y")
	echo "Date: $DATE" | tee -a $HOME/scripts/keys-refresh.txt
	TIME=$(date +"%r")
	echo "Time: $TIME" | tee -a $HOME/scripts/keys-refresh.txt
	echo
	sleep 2 | tee -a $HOME/scripts/keys-refresh.txt

	echo "Initializing keys. . ." | tee -a $HOME/scripts/keys-refresh.txt
	echo $pswd | sudo -S pacman-key --init | tee -a $HOME/scripts/keys-refresh.txt
	echo
	sleep 2 | tee -a $HOME/scripts/keys-refresh.txt
	
	echo -e "${COLOR}"
	echo "Populating archlinux. . ." | tee -a $HOME/scripts/keys-refresh.txt
	sudo pacman-key --populate archlinux | tee -a $HOME/scripts/keys-refresh.txt
	echo
	sleep 2 | tee -a $HOME/scripts/keys-refresh.txt

	echo -e "${COLOR}"
	echo "Refreshing keys. . ." | tee -a $HOME/scripts/keys-refresh.txt
	sudo pacman-key --refresh-keys 2>&1 | tee -a $HOME/scripts/keys-refresh.txt
	echo
	sleep 2 | tee -a $HOME/scripts/keys-refresh.txt

	echo -e "${COLOR}"
	echo "Updating databases. . ." 2>&1 | tee -a $HOME/scripts/keys-refresh.txt
	sudo pacman -Syy | tee -a $HOME/scripts/keys-refresh.txt
	echo
	sleep 2 | tee -a $HOME/scripts/keys-refresh.txt
}

refresh
echo -e "${RESTORE}"
exit 0
