#!/bin/bash

# Bash Color Random
COLOR="\033[1;38;5;$((RANDOM % 255+1))m"
RESTORE='\033[0m'

psw='spike'
echo -e "${COLOR}"
echo "Updating repos. . ."
sleep 2

# Registering sudo and updating repos
echo $psw | sudo -S pacman -Sy
pacaur --noconfirm --noedit -Syy
pacaur --noconfirm --noedit -Syu
echo
sleep 2
echo -e "${RESTORE}"
# Ask if restore with --needed only or reinstall everything
read -t 10 -p "Would you like to use the '--needed' options? You have 10 seconds to decide and installing and reinstalling everything.[y/n]: " needed
case "$needed" in
	y|Y)
		echo -e "${COLOR}"
		echo "Ok using --needed option. . ."
		sleep 2
		echo -e "${RESTORE}"
		pacaur -S --needed --noedit $(< /home/msifland/pkg_bkups/pkglist-off.txt)
	;;
	n|N)
		echo -e "${COLOR}"
		echo "Ok not using --needed option. . ."
		sleep 2
		echo -e "${RESTORE}"
		pacaur -S --noedit $(< /home/msifland/pkg_bkups/pkglist-off.txt)
	;;
	*)
		echo -e "${COLOR}"
		echo "Timed out not using --needed option and reinstalling everything. . ."
		sleep 2
		echo -e "${RESTORE}"
		pacaur -S --noedit $(< /home/msifland/pkg_bkups/pkglist-off.txt)
esac
echo
sleep 2
echo -e "${RESTORE}"
# Ask if would like to install AUR packages
read -t 10 -p "Would you like to reinstall AUR packages? You have 10 seconds to decide and reinstalling everything.[y/n]: " AUR
echo -e "${COLOR}"
case "$AUR" in
	y|Y)
		echo "Ok, reinstalling AUR packages. . ."
		echo
		sleep 2
		echo -e "${RESTORE}"
		# Ask if restore with --needed only or reinstall everything
		read -t 10 -p "Would you like to use the '--needed' options? You have 10 seconds to decide and installing and reinstalling everything.[y/n]: " needed
		echo -e "${COLOR}"
		case "$needed" in
		y|Y)
			echo "Ok using --needed option. . ."
			sleep 2
			echo -e "${RESTORE}"
			pacaur -S --needed --noedit $(< /home/msifland/pkg_bkups/pkglist-loc.txt)
		;;
		n|N)
			echo "Ok not using --needed option. . ."
			sleep 2
			echo -e "${RESTORE}"
			pacaur -S --noedit $(< /home/msifland/pkg_bkups/pkglist-loc.txt)
		;;
		*)
			echo "Timed out not using--needed option and reinstalling everything. . ."
			sleep 2
			echo -e "${RESTORE}"
			pacaur -S --noedit $(< /home/msifland/pkg_bkups/pkglist-loc.txt)
		esac

	;;
	n|N)
		echo "Ok not reinstalling AUR packages. . ."
	;;
	*)
		echo "Timed out, reinstalling all AUR packages. . ."
		echo -e "${RESTORE}"
		pacaur -S --noconfirm --noedit $(< /home/msifland/pkg_bkups/pkglist-loc.txt)
esac

echo
sleep 2
echo -e "${COLOR}"
echo "All Done, Check For Errors. . ."
echo -e "${RESTORE}"
exit 0

