#!/bin/bash

echo "spike" | sudo -S systemctl stop teamviewerd
sleep 120

sudo systemctl start teamviewerd
echo
echo "Done..."

#Nohup at beginning and & at end completely screen nohupes from shell
nohup teamviewer &
#Other options:
#teamviewer &; disown
#teamviewer <&- &
