#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
if [[ -d $HOME/Downloads/linux-firmware ]]; then
	rm -rf $HOME/Downloads/linux-firmware
fi
echo
echo "Getting i915 Linux Firmware. . ."
sleep 1
cd $HOME/Downloads
git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
cd linux-firmware
sleep 1

echo
read -p "Would you like to copy i915 firmware files to /lib/firmware/? " YNI915
echo
if [[ $YNI915 =~ ^([yY][eE][sS]|[yY])$ ]]; then
	echo "Copying i915 to /lib/firmware. . ."
	sudo cp -rf i915 /lib/firmware/
	sleep 1
else
	echo
	echo "Ok, not copying now..."
	sleep 1
fi

echo
read -p "Would you like to copy nvidia firmware files to /lib/firmware/? " YNNVID
echo
if [[ $YNNVID =~ ^([yY][eE][sS]|[yY])$ ]]; then
	echo
	echo "Copying nvidia to lib/firmware. . ."
	sudo cp -rf nvidia /lib/firmware/
	sleep 1
else
	echo
	echo "Ok, not copying now..."
	sleep 1
fi

cd ..
rm -rf linux-firmware

cd
echo
sudo update-initramfs -c -k all
echo
sudo update-grub
