#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
if [[ -d $HOME/Downloads/linux-firmware ]]; then
	rm -rf $HOME/Downloads/linux-firmware
fi
echo
echo "Getting i915 Linux Firmware. . ."
sleep 1
cd $HOME/Downloads
git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
cd linux-firmware
sleep 1

echo
echo "Copying i915 to /lib/firmware. . ."
sudo cp -rf i915 /lib/firmware/
sleep 1

echo
echo "Copying nvidia to lib/firmware. . ."
sudo cp -rf nvidia /lib/firmware/
sleep 1

cd ..
rm -rf $HOME/Downloads/linux-firmware

cd
echo
echo 'spike' | sudo -S update-initramfs -c -k all
echo
sudo update-grub
