#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.

# Commented out some lines here. Currently runnign this script with crontab. If you wish to run it every 24 hours from computer start and an entry to start up apps and uncomment these lines.
#echo
#sleep 120

#while true; do
	# The 'source .zshrc' parts allows for sudo running.
	xfce4-terminal -e "zsh -c \"source .zshrc; echo 'y' | $HOME/scripts/kernel_scripts/kernel-update; sleep 60\""
#	sleep 24h
#done

