#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.

INST_FILE="$HOME/.config/autostart/nvidia-kernel-build.desktop"

cat << EOF > $INST_FILE
[Desktop Entry]
Type=Application
Exec=/usr/bin/env /usr/bin/xterm -e 'bash -c "PATH=/usr/bin:/usr/sbin:/bin:/sbin:$PATH; echo \\\"Building nvidia-kernel for newly installed kernel.\\\"; echo 'spike' | sudo -S module-assistant auto-install --force nvidia-legacy-390xx-kernel; echo 'spike' | sudo -S update-grub; echo; echo \\\"Finished building nvidia-kernel for current kernel.\\\"; rm -rf $HOME/.config/autostart/nvidia-kernel-build.desktop; echo 'spike' | sudo -S shutdown -r now"'
Hidden=false
X-MATE-Autostart-enabled=true
Name[en_US]=nvidia-kernel-build
Name=nvidia-kernel-build
Comment[en_US]=
Comment=
X-MATE-Autostart-Delay=60
EOF
