#!/bin/bash
# This is a blank bash script document.
# Put your code below this line.
VERSION=""
if [[ -d "$HOME/tmp/perf-package" ]]; then
	rm -rf $HOME/tmp/perf-package
fi
mkdir $HOME/tmp/perf-package

echo 'spike' | sudo -S -v
sudo apt-get install --yes libaudit-dev libslang2-dev libelf-dev libdw-dev libnuma-dev libunwind-dev libperl-dev libiberty-dev asciidoc binutils-dev flex bison

make -C tools/perf/ install DESTDIR=$HOME/tmp/perf-package/linux-perf-${VERSION}/usr


cd $HOME/tmp/perf-package/
mkdir -p linux-perf-${VERSION}/DEBIAN

cat << EOF > linux-perf-${VERSION}/DEBIAN/control
Package: linux-perf-$VERSION
Source: linux
Version: ${VERSION}
Architecture: amd64
Maintainer: Kopeio Kernel Team <kernel@kopeio.org>
Depends: libaudit1 (>= 1:2.2.1), libc6 (>= 2.14), libc6-i386 (>= 2.7), libc6-x32 (>= 2.16), libdw1 (>= 0.157), libelf1 (>= 0.144), libnuma1, libperl5.26 (>= 5.26.0), libpython2.7 (>= 2.7), libslang2 (>= 2.2.4), libunwind8, zlib1g (>= 1:1.1.4)
Recommends: linux-base
Suggests: linux-doc-$VERSION
Conflicts: linux-tools-$VERSION
Replaces: linux-tools-$VERSION
Provides: linux-tools-$VERSION
Section: devel
Priority: optional
Homepage: https://www.kernel.org/
Description: Performance analysis tools for Linux $VERSION
 This package contains the 'perf' performance analysis tools for Linux
 kernel version $VERSION.
 .
 The linux-base package contains a 'perf' command which will invoke the
 appropriate version for the running kernel.
EOF

cat << EOF > linux-perf-${VERSION}/DEBIAN/conffiles
EOF

cd  linux-perf-${VERSION}/
mkdir -p usr/lib
mv usr/bin/perf usr/bin/perf_$VERSION
# TODO: rename usr/libexec to usr/lib ?
mv usr/libexec/perf-core usr/lib/perf_$VERSION-core
# TODO: rename usr/lib64 to usr/lib ?
mv usr/lib64/traceevent usr/lib/traceevent_$VERSION
mkdir -p usr/share/bash-completion/completions/
mv ./usr/etc/bash_completion.d/perf usr/share/bash-completion/completions/perf_$VERSION
# TODO: missing?
mkdir -p usr/share/doc
mv usr/share/doc/linux-perf usr/share/doc/linux-perf-$VERSION
# TODO: missing?
mv usr/share/lintian/overrides/linux-perf usr/share/lintian/overrides/linux-perf-$VERSION
find usr/share/man -type f | xargs rename  "s/perf/perf_$VERSION/"
find usr/share/man -type f | xargs gzip
mv usr/share/perf-core usr/share/perf_$VERSION-core
# TODO: keep?

rm -f ./usr/lib64/libperf-gtk.so

cd ..

fakeroot dpkg-deb --build linux-perf-${VERSION}/

read -p "Press 'ENTER' or close this window to exit and install perf package."
