#!/bin/bash
# This script runs ****your script**** from cron. Needed to run in terminal. Put you crontab -e job as a path to this script. The 'read -n1' at the end(bash read syntax), is to hold the window open. environment is copied from the env scripts.
env $(cat ~/scripts/cron_scripts/env-environment) /usr/bin/mate-terminal -e "bash -c \"source ~/.bashrc; clear; $HOME/scripts/****your script**** 2>&1 | tee $HOME/scripts/cron_scripts/****your script****.log; subl $HOME/scripts/cron_scripts/****your script****.log\""
