#!/bin/bash
# This script runs ****your script**** from cron. Needed to run in terminal. Put you crontab -e job as a path to this script.
env $(cat /home/msifland/scripts/cron_scripts/env-environment) /usr/bin/mate-terminal -e "zsh -c \"source .zshrc; clear; $HOME/scripts/linux-update; read -s\""
