#!/bin/bash
# This script runs ****your script**** from cron. Needed to run in terminal. Put you crontab -e job as a path to this script.
export DISPLAY=:0
/usr/bin/konsole -e zsh -c "source .zshrc; clear; upgrade_oh_my_zsh; read -s"
