#!/bin/bash
# This script runs ****your script**** from cron. Needed to run in terminal. Put you crontab -e job as a path to this script. The 'read -s' at the end(bash read syntax), is to hold the window open.(read -n1 for bash syntax). environment is copied from the env scripts.
env $(cat /home/msifland/scripts/cron_scripts/env-environment) /usr/bin/mate-terminal -e "bash -c \"source /home/msifland/.bashrc; clear; $HOME/scripts/screenfetch-update; read -s\""
