#!/bin/bash
# This script runs /scripts/virus-freshclam from cron. Needed to run in terminal. Put you crontab -e job as a path to this script. The 'read -n1' at the end(bash read syntax), is to hold the window open.(read -n1 for bash syntax). environment is copied from the env scripts.
env $(cat ~/scripts/cron_scripts/env-environment) /usr/bin/mate-terminal -e "bash -c \"source ~/.bashrc; clear; $HOME/scripts/virus-freshclam 2>&1 | tee $HOME/scripts/cron_scripts/virus-freshclam.log; /usr/bin/pluma $HOME/scripts/cron_scripts/virus-freshclam.log\""
