#!/bin/bash
# This script runs virus-clamscan from cron. Needed to run in terminal

export DISPLAY=$(w $(id -un) | awk '{print $2}' | sed '/up/d' | sed '/TTY/d')
export GNOME_DESKTOP_SESSION_ID=true
DBUS_SESS=$(sed -zne 's/^DBUS_SESSION_BUS_ADDRESS=//p' /proc/`pgrep gnome-session -U $(id -u)`/environ)
export DBUS_SESSION_BUS_ADDRESS="$DBUS_SESS"

/usr/bin/gnome-terminal -- zsh -c "source .zshrc; clear; $HOME/scripts/virus-clamscan; read -s"
